plugin:
    name: acornassociated.messaging::lang.plugin.name
    description: acornassociated.messaging::lang.plugin.description
    author: 'Acorn Associated'
    icon: wn-icon-wechat
    replaces: {  }
permissions:
    acornassociated_messaging:
        label: acornassociated.messaging::lang.permissions.view_messages
        tab: acornassociated.messaging::lang.plugin.name
navigation:
    messaging-menu-item:
        label: acornassociated.messaging::lang.plugin.name
        url: acornassociated/messaging/conversations
        icon: icon-wechat
        permissions:
            - acornassociated_messaging
