# ===================================
#  Configures the messsage list widget
# ===================================

titleProperty: 'first_name'
descriptionProperty: none
descriptionProperties:
    groups: groups
    email: email
    is_superuser: is_superuser
    last_message_at_string: last_message_at_string
    message_count: message_count
noRecordsMessage: acorn.messaging::lang.models.conversation.empty
deleteConfirmation: 'cms::lang.page.delete_confirm_multiple'
itemType: conversation
sortingProperties:
    first_name: acorn.messaging::lang.models.conversation.sorting.first_name
    last_name: acorn.messaging::lang.models.conversation.sorting.last_name
    email_lcase: acorn.messaging::lang.models.conversation.sorting.email
    last_message_at: acorn.messaging::lang.models.conversation.sorting.date
    message_count: acorn.messaging::lang.models.conversation.sorting.count
    item_type: acorn.messaging::lang.models.conversation.sorting.type
